"""
BAS-APG — Recovery Engine

Generates recovery guidance from predefined templates when deviations occur.

CRITICAL DESIGN RULE:
  Recovery paths are PREDEFINED, not generated by AI/LLM.
  We NEVER invent scientific instructions at runtime.
  The recovery guidance comes from templates + procedure schema data.
"""

class RecoveryEngine:
    """Generates human-readable recovery guidance from templates.

    All recovery text is deterministic — same inputs always produce
    the same output. No LLM, no AI, no randomness.
    """

    
    TEMPLATES = {
        "WRONG_OBJECT": (
            "Incorrect object detected. "
            "You used {observed}, but step {step_id} requires {expected}. "
            "Please put down the {observed} and pick up the {expected}."
        ),
        "SKIPPED_STEP": (
            "Steps were skipped. "
            "Please go back and complete step {step_id}: {description}. "
            "The procedure must be followed in order."
        ),
        "WRONG_ORDER": (
            "Steps performed out of order. "
            "Please return to step {step_id}: {description}. "
            "Complete this step before proceeding."
        ),
        "INCOMPLETE_ACTION": (
            "Step {step_id} has timed out. "
            "Please complete the action: {description}. "
            "Expected action is {action} on {object}."
        ),
    }

    
    VOICE_TEMPLATES = {
        "WRONG_OBJECT": (
            "Warning. Wrong object. Use {expected} instead of {observed}."
        ),
        "SKIPPED_STEP": ("Warning. Step {step_id} was skipped. Complete it first."),
        "WRONG_ORDER": ("Warning. Wrong order. Return to step {step_id}."),
        "INCOMPLETE_ACTION": (
            "Attention. Step {step_id} timed out. Please complete {action} on {object}."
        ),
    }

    def generate_recovery(
        self,
        deviation_type: str,
        current_step,
        observed_object: str = "",
    ) -> dict:
        """Generate recovery guidance for UI and voice.

        Args:
            deviation_type: WRONG_OBJECT | SKIPPED_STEP | WRONG_ORDER | INCOMPLETE_ACTION
            current_step: StepDefinition that was expected.
            observed_object: What was actually detected (for WRONG_OBJECT).

        Returns:
            dict with keys: ui_text (detailed), voice_text (short), severity
        """
        format_kwargs = {
            "step_id": current_step.step_id,
            "action": current_step.action,
            "object": current_step.object,
            "expected": current_step.object,
            "observed": observed_object or "unknown",
            "description": current_step.description,
        }

        ui_template = self.TEMPLATES.get(
            deviation_type, "Unknown deviation detected. Please check your procedure."
        )
        voice_template = self.VOICE_TEMPLATES.get(
            deviation_type, "Warning. Deviation detected."
        )

        severity = self._get_severity(deviation_type)

        return {
            "ui_text": ui_template.format(**format_kwargs),
            "voice_text": voice_template.format(**format_kwargs),
            "severity": severity,
            "deviation_type": deviation_type,
            "recovery_options": (
                current_step.recovery_options
                if hasattr(current_step, "recovery_options")
                else ["voice_prompt"]
            ),
        }

    @staticmethod
    def _get_severity(deviation_type: str) -> str:
        """Map deviation type to severity level."""
        severity_map = {
            "WRONG_OBJECT": "error",
            "SKIPPED_STEP": "critical",
            "WRONG_ORDER": "warning",
            "INCOMPLETE_ACTION": "warning",
        }
        return severity_map.get(deviation_type, "warning")

    @staticmethod
    def find_last_valid_step(completed_steps: list[str]) -> str | None:
        """Return the step_id of the last successfully completed step."""
        return completed_steps[-1] if completed_steps else None
